# Generated by Django 4.2.6 on 2024-10-05 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_chatroom_code_remove_chatroom_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
