<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-10-04 17:41
=======
# Generated by Django 5.0.7 on 2024-10-04 18:08
>>>>>>> cb3b136a7e7415044e51c2774183408c7297a04b

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_domain_user_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodTesting_Scan_Image',
        ),
        migrations.DeleteModel(
            name='FoodTesting_Scan_text',
        ),
    ]
