# Generated by Django 5.0.7 on 2024-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
