<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-10-04 17:41
=======
# Generated by Django 5.0.7 on 2024-10-04 18:08
>>>>>>> cb3b136a7e7415044e51c2774183408c7297a04b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
